name: edgarholguin
favicon: null
layout_spectrum: 0.24816
typography_spectrum: 0.5683890592772514
title: edgarholguin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#575757'
    - '#8e8e8e'
    - '#b1b1b1'
    - '#f8f8f8'
  brandStrength: 0.875
  lightness: 0.9456976801156998
  saturation: 0.6875
  rhythmicContrast: 0.056644396390765905
purpose: []
